# Generated by Django 2.0.6 on 2019-09-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradedcwapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('realname', models.CharField(max_length=150)),
                ('accountNumber', models.IntegerField(max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=150)),
            ],
        ),
    ]
