# Generated by Django 2.0.6 on 2019-09-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradedcwapp', '0002_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountNumber',
            field=models.IntegerField(),
        ),
    ]
